### PR TITLE
Update for "Discworld" and "Good Omens"

### PR DESCRIPTION
**Pull request by jforget**
I feel I have to react to the news from last Thursday.

On a technical note: why does this pull request mention older commits, which do not apply to the two modified files?

### CODE REVIEW

**Comment by book** [comment]
I didn't merge your previous contribution, but cherry-picked the commits. So instead of doing a pull, you basically needed to reset your master branch to follow mine.

Don't worry, I'll only pick the relevant commits for this too.

**Comment by book** [comment]
I've included the relevant commits as ffa9ced0e89ebb24872057428fd791fd03ab910e and 458b85de8461717739ba060f6ddc31894b7060ec.

Thanks!

**Comment by book** [comment]
Now that the file is in UTF-8, what about using the Unicode small caps for the Death quote? Using those `LATIN LETTER SMALL CAPITAL ...` codepoints.

**Comment by book** [comment]
Except `LATIN LETTER SMALL CAPITAL Q` seems to be missing from Unicode...

**Comment by jforget** [comment]
Le dimanche 07 juin 2015 à 17:28 -0700, Philippe Bruhat (BooK) a écrit :
> Now that the file is in UTF-8, what about using the Unicode small caps
> for the Death quote? Using those LATIN LETTER SMALL CAPITAL ...
> codepoints.
> 
> —
> Reply to this email directly or view it on GitHub.

I do not remember any Pratchett book in which Death speaks with
small caps. He always speaks with normal uppercase letters.

Jean

**Comment by book** [comment]
Then I guess I was misled by [wikipedia](https://en.wikipedia.org/wiki/Terry_Pratchett#Death).

I'll close the issue, then.

**Pull request closed without merging**
